### ISSUE TITLE
Difference between cache and non cache series with resample operator

### ISSUE THREAD

**Issue by EngieAntoine** [pythonianfr/tshistory_refinery#2]
On some formulas, there are difference between cache and non cached series.

For example, the serie gas.de.demand.g2p.entsoe.gwhd.obs : 
![image](https://user-images.githubusercontent.com/121629262/215041239-4c6ab621-9d00-47f8-b5a9-fbc6a0585d6d.png)

here the formula of this serie : 
```
(slice
    (/
        (/
            (*
                24
                (**resample**
                    (naive
                        (time-shifted
                            (cronos "c6f82af2-e5e8-48f3-921d-cb2c81d8140d")
                            #:hours -6)
                        "CET")
                    "D"))
            0.5)
        1000)
    #:todate (shifted (today) #:days -1))
```
The cronos operator can retrieve data each quarter.

The cache policy used : 
![image](https://user-images.githubusercontent.com/121629262/215041836-3892ca21-6423-4a46-8923-8f2a2c8befd7.png)

After investigating, there are multiple problem/enhancement we need to cover this kind of formula (with the use of resample operator and rev date each hours) : 
1. init revision day : because we don't want a fixed initial revision date, we used the following syntax : 
`(shifted (today) #:days -7)`. the **(today)** isn't a real **today**, it's a **now()** with the hours/minutes/seconds. And it's a problem because of the mean by day (operator resample with "D") on the first date isn't correct if you don't take all data on the first day depending of when you launch the initial fill of the cache.

2. rev date rule is `0 * * * *`. So it's mean we want cached revision date each hours. But, same than before, when we evaluated the formula (eval_formula) we need evaluate the **look after** and **look before** parameters. In our case, we used the following syntax : `(shifted now #:days -7)`. The problem is that the 'now' syntax mean the different revdate we have to evaluate as you can see in the code :
```python
from_value_date = eval_moment(
                policy['look_before'],
                {'now': revdate}
            )
```
Same that before, the first value date will be not correct because of the resample in the formula (here revdate is a datetime with hours because of the revision date rule. 
So we need, to have **now_day_full** syntax which take all the day and not only from the hour of the revdate.
With the following modification, it's work but the problem will remain if have resample on a month for example.
```python
# testing local fix
revdate_without_hour = revdate.replace(hour=0)
from_value_date = eval_moment(
    policy['look_before'],
    {'now': revdate_without_hour,
     }
)
```
A more elegant way, must be something like :
```python
revdate_without_hour = revdate.replace(hour=0)
from_value_date = eval_moment(
    policy['look_before'],
    {'now': revdate,
     'now_full_day':revdate_without_hour
     }
)
```
but the elm gui don't allow to modify the syntax with a `(shifted **now_full_day** #:days -7)`...

I tried to provide an unit test that produced this "_bug_". 

3. the last problem encountered is not directly link to this problem but we discovered it : via the tsinfo, even if you uncheck the cache button you don't see the real non cached version. This is the reason we have to create nocache_series.
Here an example with gas.de.demand.g2p.entsoe.gwhd.obs formula

cached serie with uncheck cache button : 
![image](https://user-images.githubusercontent.com/121629262/215047411-0b74d508-975b-42e9-836c-ebb15e88f78b.png)
(last value date missing)

same serie without using cache : 
![image](https://user-images.githubusercontent.com/121629262/215047115-3d38b0ca-9ea7-43b4-a0e0-1e7fc648911b.png)

**Comment by EngieAntoine** [comment]
I pushed the unit test test_cache_resample on test_autotrophic_cache_refresh branch

**Comment by zogzog** [comment]
Many thanks. I'll have a look asap.

**Comment by zogzog** [comment]
After some discussion with Arnaud we think it is indeed related to the `resample` operator.

It is buggy with query parameters and always has been. The cache vs nocache situation makes it appear in the daylight.
The right solution to this I believe is not in twisting the cache policy parameters (a workaround that won't let the root issue go away) but fixing resample itself.

By chance, the framework to provide the fix lies in the "scopes" interpreter feature.

The idea is like this: the resample operator, to work well, needs more data (left and right) than what the query strictly provides. The solution is to query a bit more to the left (and right). The exact amount to extra checkout probably depends on the granularity of the resampling operation.

Explaining this in detail is a bit tricky. I think it was Octave that got the most complete info on the scopes system. If that can help we can schedule a call in person and I will explain how that works - with examples.

**Comment by EngieAntoine** [comment]
Yes I think a call can help. Available when you want this week

**Comment by EngieAntoine** [comment]
I push a bugfix/resample branch and a create a pull request.

**Comment by zogzog** [comment]
I'll have a look tomorrow.

**Comment by zogzog** [comment]
Work was pushed on tshistory_formula.
